### ISSUE TITLE
grunt: not found

### ISSUE THREAD

**Issue by HaiderMalik12** [jasancheg/sails-angular-electron#1]
I am trying to run this project.I am getting this error.

sh: 1: grunt: not found

npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v5.5.0/bin/node" "/home/ubuntu/.nvm/versions/node/v5.5.0/bin/npm" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! sails-angular-electron@0.0.1 start: `grunt start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sails-angular-electron@0.0.1 start script 'grunt start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sails-angular-electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt start
npm ERR! You can get their info via:
npm ERR!     npm owner ls sails-angular-electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

  }).flatten().uniq().value();
       ^

TypeError: _(...).map(...).flatten is not a function
    at Object.module.exports [as findup](/home/ubuntu/workspace/node_modules/findup-sync/lib/findup-sync.js:33:8)
    at Task.task.init (/home/ubuntu/workspace/node_modules/grunt/lib/grunt/task.js:427:16)
    at Object.grunt.tasks (/home/ubuntu/workspace/node_modules/grunt/lib/grunt.js:120:8)
    at Object.module.exports [as cli](/home/ubuntu/workspace/node_modules/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v5.5.0/lib/node_modules/grunt-cli/bin/grunt:44:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

**Comment by julienazerty** [comment]
@HaiderMalik12 Did you managed to make it works ? I need to make a sailsjs api with electronjs inside.
